exp: "Animation_1"
init_ckpt: data/sphere.pt
mesh: "data/Anim_1/"
logdir: "logs/"

num_frames: 5
num_views: 100
res: 256
epochs: 1500
iters: 1
batch_size: 8192
eps: 0.0001
mesh_res_base: 150
mesh_res_limit: 200
fine_e: 1000
max_v: 3000000
lambda_: 100
max_laplace_lam: 0.0
min_laplace_lam: 0.0
vol_lambda: 0.1
num_vol_points: 16384
weight_decay: 0.1
lr: 0.000002
scale: 1.7

img_log_freq: 100
mesh_log_freq: 50
ckpt_log_freq: 100

ls:
    lambda_: 19
    alpha: 0.9
    remesh: false
