exp: "FIT_TO_STATIC_VSPHERE"

mesh: "data/VSphere/"                    # Only for synthetic mode. In other modes, it will be ignored
logdir: "logs/"
dataset_type: "synthetic"                # moving_person | synthetic

_continue: False                                                  # Continue from a specified checkpoint
folder_name:                                                      # If _continue: True, this folder specifies the folder in which your logs are stored
last_epoch:                                                       # If _continue: True, this shows the last epoch that your model was trained until previously
init_ckpt:                                                        # Only change it to sth other than None if you are doing _continue: True

num_frames: 10
num_views: 10
res: 256
epochs: 3000
iters: 1
batch_size: 8192
batch_size_for_mc: 20000
eps: 0.0001
mesh_res_base: 200
mesh_res_limit: 256
fine_e: 1000
max_v: 7500000

lr: 0.0001
render_lr: 0.000001
scale: 1.7

####### Render Coloured #######
with_texture: False

####### DEPTH #######
include_depth: False
lambda_depth: 0

####### REGULARIZATIONS #######
max_laplace_lam: 0.0002
min_laplace_lam: 0.0
ssim_lam: 0.02
eikonal_lam: 0.001              # coefficient for eikonal loss | Prev working val: 0.0 | 0.001
initial_df_dt_lam: 0.05         # coefficient for df/dt in every epoch (it is a damping_factor. see: get_damping_factor in utils.py for more)

####### LOGGING #######
video_log_freq: 1000
img_log_freq: 50
mesh_log_freq: 50
mesh_save_freq: 300
ckpt_log_freq: 100
tensorboard_mesh_log_freq: 150
evaluate_intermediate_times_every: 100

####### LR SCHEDULERS #######
use_schedulers: False

# LINEAR WARMUP
warmup_epochs: 0
warmup_coeff: 0

fixed_epoch_to_start: 900
fixed_lr: 0.000002

####### AUTOMATIC MIXED PRECISION #######
use_amp: True
