exp: "SINGLEFRAME_STATIC_SCREAMING_FACE"

mesh: "data/Static_Screaming_Face/"                     
logdir: "logs/"
dataset_type: "synthetic"               

_continue: False                         # Continue from a specified checkpoint
folder_name: 1_SINGLEFRAME_STATIC_SCREAMING_FACE                           # If _continue: True, this folder specifies the folder in which your logs are stored
last_epoch:  2900                            # If _continue: True, this shows the last epoch that your model was trained until previously

num_frames: 1
num_views: 50
num_sample_views_for_splats: 1
res: 256
epochs: 3500
iters: 1
batch_size: 20_480
batch_size_for_mc: 20_000
eps: 0.0001
mesh_res_base: 150
mesh_res_limit: 175
fine_e: 1000
max_v: 7_500_000

lr: 0.00005
render_lr: 0.0002
scale: 1.7

####### Render Coloured #######
with_texture: False

####### DEPTH #######
include_depth: False
lambda_depth: 0

####### REGULARIZATIONS #######
max_laplace_lam: 0.0001
min_laplace_lam: 0.0
ssim_lam: 0.01
eikonal_lam: 0.001              # coefficient for eikonal loss 
initial_df_dt_lam: 0.05         # Can also be 0.0 | coefficient for df/dt in every epoch (it is a damping_factor. see: get_damping_factor in utils.py for more)


####### LOGGING #######
video_log_freq: 1000
img_log_freq: 1
mesh_log_freq: 50
mesh_save_freq: 300
ckpt_log_freq: 100
tensorboard_mesh_log_freq: 150
evaluate_intermediate_times_every: 100

####### AUTOMATIC MIXED PRECISION #######
use_amp: True